search:
  kakao:
    api:
      url: "https://dapi.kakao.com/v2/search/blog"
      key: "KakaoAK ce330f1cdf6b8d090fae0393f5a38dd0"
  naver:
    api:
      url: "https://openapi.naver.com/v1/search/blog.json"
      id: "V0hOILRuRgtkiCbXH5Nu"
      secret: "186VZBNajT"

logging:
  level:
    root: info
    com.sixthou.blogsearchstandalone: debug

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
